In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
dataset = pd.read_csv(r'C:\Users\PRATHEEK POOJARY\OneDrive\Desktop\Machine Learning\datasets\Melbourne_housing_FULL.csv')
dataset.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object
 6   SellerG        34857 non-null  object
 7   Date           34857 non-null  object
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object
 17  Lattitude      26881 non-null  float64
 18  Longtitude     26881 non-null  float64
 19  Regionname     34854 non-null  object
 20  Propertycount  34854 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 5.6+ MB

In [5]:
cols_to_use = ['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Regionname', 'Propertycount', 
               'Distance', 'CouncilArea', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'Price']
dataset = dataset[cols_to_use]
dataset.head()

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,SS,Jellis,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,126.0,NaN,NaN
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.0,NaN,1480000.0
2,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.0,79.0,1035000.0
3,Abbotsford,3,u,VB,Rounds,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,0.0,NaN,NaN
4,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.0,150.0,1465000.0

In [6]:
dataset.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           3
Propertycount        3
Distance             1
CouncilArea          3
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
Price             7610
dtype: int64

In [7]:
cols_to_fill_zero = ['Propertycount', 'Distance', 'Bedroom2', 'Bathroom', 'Car']
dataset[cols_to_fill_zero] = dataset[cols_to_fill_zero].fillna(0)

dataset['Landsize'] = dataset['Landsize'].fillna(dataset['Landsize'].mean())
dataset['BuildingArea'] = dataset['BuildingArea'].fillna(dataset.BuildingArea.mean())

In [8]:
dataset.isnull().sum()

Suburb              0
Rooms               0
Type                0
Method              0
SellerG             0
Regionname          3
Propertycount       0
Distance            0
CouncilArea         3
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
Price            7610
dtype: int64

In [9]:
dataset.dropna(inplace=True)

In [10]:
dataset.isnull().sum()

Suburb           0
Rooms            0
Type             0
Method           0
SellerG          0
Regionname       0
Propertycount    0
Distance         0
CouncilArea      0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
Price            0
dtype: int64

In [ ]:
dataset= pd.get_dummies(dataset,drop_first=True,dtype=int,)

In [22]:
for col in dataset:
    print(f"{col}: {dataset[col].values}")

Rooms: [2 2 3 ... 2 3 2]
Propertycount: [4019. 4019. 4019. ... 6543. 6543. 6543.]
Distance: [2.5 2.5 2.5 ... 6.3 6.3 6.3]
Bedroom2: [2. 2. 3. ... 2. 0. 2.]
Bathroom: [1. 1. 2. ... 1. 0. 1.]
Car: [1. 0. 0. ... 2. 0. 0.]
Landsize: [202.         156.         134.         ... 220.         593.59899336
 250.        ]
BuildingArea: [160.25640036  79.         150.         ... 120.         160.25640036
 103.        ]
Price: [1480000. 1035000. 1465000. ...  705000. 1140000. 1020000.]
Suburb_Aberfeldie: [False False False ... False False False]
Suburb_Airport West: [False False False ... False False False]
Suburb_Albanvale: [False False False ... False False False]
Suburb_Albert Park: [False False False ... False False False]
Suburb_Albion: [False False False ... False False False]
Suburb_Alphington: [False False False ... False False False]
Suburb_Altona: [False False False ... False False False]
Suburb_Altona Meadows: [False False False ... False False False]
Suburb_Altona North: [False False False ... False False False]
Suburb_Ardeer: [False False False ... False False False]
Suburb_Armadale: [False False False ... False False False]
Suburb_Ascot Vale: [False False False ... False False False]
Suburb_Ashburton: [False False False ... False False False]
Suburb_Ashwood: [False False False ... False False False]
Suburb_Aspendale: [False False False ... False False False]
Suburb_Aspendale Gardens: [False False False ... False False False]
Suburb_Attwood: [False False False ... False False False]
Suburb_Avondale Heights: [False False False ... False False False]
Suburb_Bacchus Marsh: [False False False ... False False False]
Suburb_Balaclava: [False False False ... False False False]
Suburb_Balwyn: [False False False ... False False False]
Suburb_Balwyn North: [False False False ... False False False]
Suburb_Bayswater: [False False False ... False False False]
Suburb_Bayswater North: [False False False ... False False False]
Suburb_Beaconsfield: [False False False ... False False False]
Suburb_Beaconsfield Upper: [False False False ... False False False]
Suburb_Beaumaris: [False False False ... False False False]
Suburb_Bellfield: [False False False ... False False False]
Suburb_Bentleigh: [False False False ... False False False]
Suburb_Bentleigh East: [False False False ... False False False]
Suburb_Berwick: [False False False ... False False False]
Suburb_Black Rock: [False False False ... False False False]
Suburb_Blackburn: [False False False ... False False False]
Suburb_Blackburn North: [False False False ... False False False]
Suburb_Blackburn South: [False False False ... False False False]
Suburb_Bonbeach: [False False False ... False False False]
Suburb_Boronia: [False False False ... False False False]
Suburb_Botanic Ridge: [False False False ... False False False]
Suburb_Box Hill: [False False False ... False False False]
Suburb_Braybrook: [False False False ... False False False]
Suburb_Briar Hill: [False False False ... False False False]
Suburb_Brighton: [False False False ... False False False]
Suburb_Brighton East: [False False False ... False False False]
Suburb_Broadmeadows: [False False False ... False False False]
Suburb_Brookfield: [False False False ... False False False]
Suburb_Brooklyn: [False False False ... False False False]
Suburb_Brunswick: [False False False ... False False False]
Suburb_Brunswick East: [False False False ... False False False]
Suburb_Brunswick West: [False False False ... False False False]
Suburb_Bulla: [False False False ... False False False]
Suburb_Bulleen: [False False False ... False False False]
Suburb_Bullengarook: [False False False ... False False False]
Suburb_Bundoora: [False False False ... False False False]
Suburb_Burnley: [False False False ... False False False]
Suburb_Burnside: [False False False ... False False False]
Suburb_Burnside Heights: [False False False ... False False False]
Suburb_Burwood: [False False False ... False False False]
Suburb_Burwood East: [False False False ... False False False]
Suburb_Cairnlea: [False False False ... False False False]
Suburb_Camberwell: [False False False ... False False False]
Suburb_Campbellfield: [False False False ... False False False]
Suburb_Canterbury: [False False False ... False False False]
Suburb_Carlton: [False False False ... False False False]
Suburb_Carlton North: [False False False ... False False False]
Suburb_Carnegie: [False False False ... False False False]
Suburb_Caroline Springs: [False False False ... False False False]
Suburb_Carrum: [False False False ... False False False]
Suburb_Carrum Downs: [False False False ... False False False]
Suburb_Caulfield: [False False False ... False False False]
Suburb_Caulfield East: [False False False ... False False False]
Suburb_Caulfield North: [False False False ... False False False]
Suburb_Caulfield South: [False False False ... False False False]
Suburb_Chadstone: [False False False ... False False False]
Suburb_Chelsea: [False False False ... False False False]
Suburb_Chelsea Heights: [False False False ... False False False]
Suburb_Cheltenham: [False False False ... False False False]
Suburb_Chirnside Park: [False False False ... False False False]
Suburb_Clarinda: [False False False ... False False False]
Suburb_Clayton: [False False False ... False False False]
Suburb_Clayton South: [False False False ... False False False]
Suburb_Clifton Hill: [False False False ... False False False]
Suburb_Clyde North: [False False False ... False False False]
Suburb_Coburg: [False False False ... False False False]
Suburb_Coburg North: [False False False ... False False False]
Suburb_Coldstream: [False False False ... False False False]
Suburb_Collingwood: [False False False ... False False False]
Suburb_Coolaroo: [False False False ... False False False]
Suburb_Craigieburn: [False False False ... False False False]
Suburb_Cranbourne: [False False False ... False False False]
Suburb_Cranbourne East: [False False False ... False False False]
Suburb_Cranbourne North: [False False False ... False False False]
Suburb_Cranbourne West: [False False False ... False False False]
Suburb_Cremorne: [False False False ... False False False]
Suburb_Croydon: [False False False ... False False False]
Suburb_Croydon Hills: [False False False ... False False False]
Suburb_Croydon North: [False False False ... False False False]
Suburb_Croydon South: [False False False ... False False False]
Suburb_Dallas: [False False False ... False False False]
Suburb_Dandenong: [False False False ... False False False]
Suburb_Dandenong North: [False False False ... False False False]
Suburb_Darley: [False False False ... False False False]
Suburb_Deepdene: [False False False ... False False False]
Suburb_Deer Park: [False False False ... False False False]
Suburb_Delahey: [False False False ... False False False]
Suburb_Derrimut: [False False False ... False False False]
Suburb_Diamond Creek: [False False False ... False False False]
Suburb_Diggers Rest: [False False False ... False False False]
Suburb_Dingley Village: [False False False ... False False False]
Suburb_Docklands: [False False False ... False False False]
Suburb_Doncaster: [False False False ... False False False]
Suburb_Doncaster East: [False False False ... False False False]
Suburb_Donvale: [False False False ... False False False]
Suburb_Doreen: [False False False ... False False False]
Suburb_Doveton: [False False False ... False False False]
Suburb_Eaglemont: [False False False ... False False False]
Suburb_East Melbourne: [False False False ... False False False]
Suburb_Edithvale: [False False False ... False False False]
Suburb_Elsternwick: [False False False ... False False False]
Suburb_Eltham: [False False False ... False False False]
Suburb_Eltham North: [False False False ... False False False]
Suburb_Elwood: [False False False ... False False False]
Suburb_Emerald: [False False False ... False False False]
Suburb_Endeavour Hills: [False False False ... False False False]
Suburb_Epping: [False False False ... False False False]
Suburb_Essendon: [False False False ... False False False]
Suburb_Essendon North: [False False False ... False False False]
Suburb_Essendon West: [False False False ... False False False]
Suburb_Eumemmerring: [False False False ... False False False]
Suburb_Eynesbury: [False False False ... False False False]
Suburb_Fairfield: [False False False ... False False False]
Suburb_Fawkner: [False False False ... False False False]
Suburb_Ferntree Gully: [False False False ... False False False]
Suburb_Ferny Creek: [False False False ... False False False]
Suburb_Fitzroy: [False False False ... False False False]
Suburb_Fitzroy North: [False False False ... False False False]
Suburb_Flemington: [False False False ... False False False]
Suburb_Footscray: [False False False ... False False False]
Suburb_Forest Hill: [False False False ... False False False]
Suburb_Frankston: [False False False ... False False False]
Suburb_Frankston North: [False False False ... False False False]
Suburb_Frankston South: [False False False ... False False False]
Suburb_Gardenvale: [False False False ... False False False]
Suburb_Gisborne: [False False False ... False False False]
Suburb_Gisborne South: [False False False ... False False False]
Suburb_Gladstone Park: [False False False ... False False False]
Suburb_Glen Huntly: [False False False ... False False False]
Suburb_Glen Iris: [False False False ... False False False]
Suburb_Glen Waverley: [False False False ... False False False]
Suburb_Glenroy: [False False False ... False False False]
Suburb_Gowanbrae: [False False False ... False False False]
Suburb_Greensborough: [False False False ... False False False]
Suburb_Greenvale: [False False False ... False False False]
Suburb_Hadfield: [False False False ... False False False]
Suburb_Hallam: [False False False ... False False False]
Suburb_Hampton: [False False False ... False False False]
Suburb_Hampton East: [False False False ... False False False]
Suburb_Hampton Park: [False False False ... False False False]
Suburb_Hawthorn: [False False False ... False False False]
Suburb_Hawthorn East: [False False False ... False False False]
Suburb_Healesville: [False False False ... False False False]
Suburb_Heatherton: [False False False ... False False False]
Suburb_Heathmont: [False False False ... False False False]
Suburb_Heidelberg: [False False False ... False False False]
Suburb_Heidelberg Heights: [False False False ... False False False]
Suburb_Heidelberg West: [False False False ... False False False]
Suburb_Highett: [False False False ... False False False]
Suburb_Hillside: [False False False ... False False False]
Suburb_Hoppers Crossing: [False False False ... False False False]
Suburb_Hughesdale: [False False False ... False False False]
Suburb_Huntingdale: [False False False ... False False False]
Suburb_Hurstbridge: [False False False ... False False False]
Suburb_Ivanhoe: [False False False ... False False False]
Suburb_Ivanhoe East: [False False False ... False False False]
Suburb_Jacana: [False False False ... False False False]
Suburb_Kalkallo: [False False False ... False False False]
Suburb_Kealba: [False False False ... False False False]
Suburb_Keilor: [False False False ... False False False]
Suburb_Keilor Downs: [False False False ... False False False]
Suburb_Keilor East: [False False False ... False False False]
Suburb_Keilor Lodge: [False False False ... False False False]
Suburb_Keilor Park: [False False False ... False False False]
Suburb_Kensington: [False False False ... False False False]
Suburb_Kew: [False False False ... False False False]
Suburb_Kew East: [False False False ... False False False]
Suburb_Keysborough: [False False False ... False False False]
Suburb_Kilsyth: [False False False ... False False False]
Suburb_Kings Park: [False False False ... False False False]
Suburb_Kingsbury: [False False False ... False False False]
Suburb_Kingsville: [False False False ... False False False]
Suburb_Knoxfield: [False False False ... False False False]
Suburb_Kooyong: [False False False ... False False False]
Suburb_Kurunjang: [False False False ... False False False]
Suburb_Lalor: [False False False ... False False False]
Suburb_Langwarrin: [False False False ... False False False]
Suburb_Laverton: [False False False ... False False False]
Suburb_Lilydale: [False False False ... False False False]
Suburb_Lower Plenty: [False False False ... False False False]
Suburb_Lynbrook: [False False False ... False False False]
Suburb_Lysterfield: [False False False ... False False False]
Suburb_MacLeod: [False False False ... False False False]
Suburb_Maidstone: [False False False ... False False False]
Suburb_Malvern: [False False False ... False False False]
Suburb_Malvern East: [False False False ... False False False]
Suburb_Maribyrnong: [False False False ... False False False]
Suburb_McKinnon: [False False False ... False False False]
Suburb_Meadow Heights: [False False False ... False False False]
Suburb_Melbourne: [False False False ... False False False]
Suburb_Melton: [False False False ... False False False]
Suburb_Melton South: [False False False ... False False False]
Suburb_Melton West: [False False False ... False False False]
Suburb_Mentone: [False False False ... False False False]
Suburb_Mernda: [False False False ... False False False]
Suburb_Mickleham: [False False False ... False False False]
Suburb_Middle Park: [False False False ... False False False]
Suburb_Mill Park: [False False False ... False False False]
Suburb_Mitcham: [False False False ... False False False]
Suburb_Monbulk: [False False False ... False False False]
Suburb_Mont Albert: [False False False ... False False False]
Suburb_Montmorency: [False False False ... False False False]
Suburb_Montrose: [False False False ... False False False]
Suburb_Moonee Ponds: [False False False ... False False False]
Suburb_Moorabbin: [False False False ... False False False]
Suburb_Mooroolbark: [False False False ... False False False]
Suburb_Mordialloc: [False False False ... False False False]
Suburb_Mount Evelyn: [False False False ... False False False]
Suburb_Mount Waverley: [False False False ... False False False]
Suburb_Mulgrave: [False False False ... False False False]
Suburb_Murrumbeena: [False False False ... False False False]
Suburb_Narre Warren: [False False False ... False False False]
Suburb_New Gisborne: [False False False ... False False False]
Suburb_Newport: [False False False ... False False False]
Suburb_Niddrie: [False False False ... False False False]
Suburb_Noble Park: [False False False ... False False False]
Suburb_North Melbourne: [False False False ... False False False]
Suburb_North Warrandyte: [False False False ... False False False]
Suburb_Northcote: [False False False ... False False False]
Suburb_Notting Hill: [False False False ... False False False]
Suburb_Nunawading: [False False False ... False False False]
Suburb_Oak Park: [False False False ... False False False]
Suburb_Oakleigh: [False False False ... False False False]
Suburb_Oakleigh East: [False False False ... False False False]
Suburb_Oakleigh South: [False False False ... False False False]
Suburb_Officer: [False False False ... False False False]
Suburb_Ormond: [False False False ... False False False]
Suburb_Pakenham: [False False False ... False False False]
Suburb_Parkdale: [False False False ... False False False]
Suburb_Parkville: [False False False ... False False False]
Suburb_Pascoe Vale: [False False False ... False False False]
Suburb_Patterson Lakes: [False False False ... False False False]
Suburb_Plenty: [False False False ... False False False]
Suburb_Plumpton: [False False False ... False False False]
Suburb_Point Cook: [False False False ... False False False]
Suburb_Port Melbourne: [False False False ... False False False]
Suburb_Prahran: [False False False ... False False False]
Suburb_Preston: [False False False ... False False False]
Suburb_Princes Hill: [False False False ... False False False]
Suburb_Research: [False False False ... False False False]
Suburb_Reservoir: [False False False ... False False False]
Suburb_Richmond: [False False False ... False False False]
Suburb_Riddells Creek: [False False False ... False False False]
Suburb_Ringwood: [False False False ... False False False]
Suburb_Ringwood East: [False False False ... False False False]
Suburb_Ringwood North: [False False False ... False False False]
Suburb_Ripponlea: [False False False ... False False False]
Suburb_Rockbank: [False False False ... False False False]
Suburb_Rosanna: [False False False ... False False False]
Suburb_Rowville: [False False False ... False False False]
Suburb_Roxburgh Park: [False False False ... False False False]
Suburb_Sandhurst: [False False False ... False False False]
Suburb_Sandringham: [False False False ... False False False]
Suburb_Scoresby: [False False False ... False False False]
Suburb_Seabrook: [False False False ... False False False]
Suburb_Seaford: [False False False ... False False False]
Suburb_Seaholme: [False False False ... False False False]
Suburb_Seddon: [False False False ... False False False]
Suburb_Silvan: [False False False ... False False False]
Suburb_Skye: [False False False ... False False False]
Suburb_South Kingsville: [False False False ... False False False]
Suburb_South Melbourne: [False False False ... False False False]
Suburb_South Morang: [False False False ... False False False]
Suburb_South Yarra: [False False False ... False False False]
Suburb_Southbank: [False False False ... False False False]
Suburb_Spotswood: [False False False ... False False False]
Suburb_Springvale: [False False False ... False False False]
Suburb_Springvale South: [False False False ... False False False]
Suburb_St Albans: [False False False ... False False False]
Suburb_St Helena: [False False False ... False False False]
Suburb_St Kilda: [False False False ... False False False]
Suburb_Strathmore: [False False False ... False False False]
Suburb_Strathmore Heights: [False False False ... False False False]
Suburb_Sunbury: [False False False ... False False False]
Suburb_Sunshine: [False False False ... False False False]
Suburb_Sunshine North: [False False False ... False False False]
Suburb_Sunshine West: [False False False ... False False False]
Suburb_Surrey Hills: [False False False ... False False False]
Suburb_Sydenham: [False False False ... False False False]
Suburb_Tarneit: [False False False ... False False False]
Suburb_Taylors Hill: [False False False ... False False False]
Suburb_Taylors Lakes: [False False False ... False False False]
Suburb_Tecoma: [False False False ... False False False]
Suburb_Templestowe: [False False False ... False False False]
Suburb_Templestowe Lower: [False False False ... False False False]
Suburb_The Basin: [False False False ... False False False]
Suburb_Thomastown: [False False False ... False False False]
Suburb_Thornbury: [False False False ... False False False]
Suburb_Toorak: [False False False ... False False False]
Suburb_Travancore: [False False False ... False False False]
Suburb_Truganina: [False False False ... False False False]
Suburb_Tullamarine: [False False False ... False False False]
Suburb_Upwey: [False False False ... False False False]
Suburb_Vermont: [False False False ... False False False]
Suburb_Vermont South: [False False False ... False False False]
Suburb_Viewbank: [False False False ... False False False]
Suburb_Wallan: [False False False ... False False False]
Suburb_Wandin North: [False False False ... False False False]
Suburb_Wantirna: [False False False ... False False False]
Suburb_Wantirna South: [False False False ... False False False]
Suburb_Warrandyte: [False False False ... False False False]
Suburb_Warranwood: [False False False ... False False False]

In [23]:
dataset.head()

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,Suburb_Aberfeldie,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
1,2,4019.0,2.5,2.0,1.0,1.0,202.0,160.2564,1480000.0,False,...,False,False,False,False,False,False,False,False,True,False
2,2,4019.0,2.5,2.0,1.0,0.0,156.0,79.0000,1035000.0,False,...,False,False,False,False,False,False,False,False,True,False
4,3,4019.0,2.5,3.0,2.0,0.0,134.0,150.0000,1465000.0,False,...,False,False,False,False,False,False,False,False,True,False
5,3,4019.0,2.5,3.0,2.0,1.0,94.0,160.2564,850000.0,False,...,False,False,False,False,False,False,False,False,True,False
6,4,4019.0,2.5,3.0,1.0,2.0,120.0,142.0000,1600000.0,False,...,False,False,False,False,False,False,False,False,True,False

In [24]:
x=dataset.drop(['Price'],axis=1)
y=dataset['Price']

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [26]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=2)

In [27]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [28]:
y_pred=model.predict(x_test)

In [29]:
model.score(x_test, y_test)

0.13853683161624675

In [30]:
model.score(x_train,y_train)

0.6827792395792723

In [31]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse:.2f}")
print(f"R² Score: {r2:.2f}")

Mean Squared Error: 342275472103.80
R² Score: 0.14

Here training score is 68% but test score is 13.85% which is very low

Normal Regression is clearly overfitting the data, let's try other models
Using Lasso (L1 Regularized) Regression Model

In [32]:
from sklearn import linear_model
modelL1 = linear_model.Lasso(alpha=50, max_iter=100, tol=0.1)
modelL1.fit(x_train, y_train)

c:\Users\PRATHEEK POOJARY\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.327e+15, tolerance: 7.963e+14
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=50, max_iter=100, tol=0.1)

In [33]:
y_predL1=modelL1.predict(x_test)

In [34]:
modelL1.score(x_train,y_train)

0.6766985624766824

In [35]:
modelL1.score(x_test,y_test)

0.6636111369404489

In [36]:
mse = mean_squared_error(y_test, y_predL1)
r2 = r2_score(y_test, y_predL1)
print(f"Mean Squared Error: {mse:.2f}")
print(f"R² Score: {r2:.2f}")

Mean Squared Error: 133653603705.64
R² Score: 0.66

Using Ridge (L2 Regularized) Regression Model

In [37]:
from sklearn.linear_model import Ridge
modelL2= Ridge(alpha=50, max_iter=100, tol=0.01)
modelL2.fit(x_train, y_train)

Ridge(alpha=50, max_iter=100, tol=0.01)

In [38]:
modelL2.score(x_train,y_train)

0.6622376739684328

In [39]:
modelL2.score(x_test,y_test)

0.6670848945194958

In [40]:
y_predL2=modelL2.predict(x_test)

In [41]:
mse = mean_squared_error(y_test, y_predL2)
r2 = r2_score(y_test, y_predL2)
print(f"Mean Squared Error: {mse:.2f}")
print(f"R² Score: {r2:.2f}")

Mean Squared Error: 132273414674.96
R² Score: 0.67